### ISSUE TITLE
Callback buffer was too small！！！

### ISSUE THREAD

**Issue by jj8401** [fyhertz/spydroid-ipcamera#17]
how can i resolve this problem？
12-08 15:18:54.286: E/Camera-JNI(32587): Callback buffer was too small! Expected 3110400 bytes, but got 38016 bytes!
12-08 15:18:54.286: E/Camera-JNI(32587): Couldn't allocate byte array for JPEG data
12-08 15:18:54.291: D/MzSplitActionBarContainer(32587): onMeasure:mBackButton=null; mMenuView=null; mEnableBackButton=false
12-08 15:18:54.291: D/MzSplitActionBarContainer(32587): onMeasure:backButtonWidth=0; menuWidth=0
12-08 15:18:54.316: E/Camera-JNI(32587): Callback buffer was too small! Expected 3110400 bytes, but got 38016 bytes!
12-08 15:18:54.316: E/Camera-JNI(32587): Couldn't allocate byte array for JPEG data
12-08 15:18:54.341: E/Camera-JNI(32587): Null byte array!
12-08 15:18:54.341: E/AndroidRuntime(32587): FATAL EXCEPTION: Thread-1037
12-08 15:18:54.341: E/AndroidRuntime(32587): Process: net.majorkernelpanic.spydroid, PID: 32587
12-08 15:18:54.341: E/AndroidRuntime(32587): java.lang.NullPointerException: Attempt to read from null array
12-08 15:18:54.341: E/AndroidRuntime(32587): 	at net.majorkernelpanic.streaming.hw.NV21Convertor.convert(NV21Convertor.java:141)
12-08 15:18:54.341: E/AndroidRuntime(32587): 	at net.majorkernelpanic.streaming.hw.NV21Convertor.convert(NV21Convertor.java:108)
12-08 15:18:54.341: E/AndroidRuntime(32587): 	at net.majorkernelpanic.streaming.video.VideoStream$2.onPreviewFrame(VideoStream.java:455)
12-08 15:18:54.341: E/AndroidRuntime(32587): 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1127)
12-08 15:18:54.341: E/AndroidRuntime(32587): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-08 15:18:54.341: E/AndroidRuntime(32587): 	at android.os.Looper.loop(Looper.java:135)
12-08 15:18:54.341: E/AndroidRuntime(32587): 	at net.majorkernelpanic.streaming.video.VideoStream$3.run(VideoStream.java:542)
12-08 15:18:54.341: E/AndroidRuntime(32587): 	at java.lang.Thread.run(Thread.java:818)

**Comment by alicanhaman** [comment]
Could be kinda late by now but check this out, 
https://github.com/fyhertz/libstreaming/issues/138

It is an issue originating from the libstreaming library which this project uses.
