### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.ads.AdView"

### ISSUE THREAD

**Issue by WestbrookZero** [fyhertz/spydroid-ipcamera#42]
2020-05-07 11:30:04.809 1684-1684/net.majorkernelpanic.spydroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.majorkernelpanic.spydroid, PID: 1684
    java.lang.RuntimeException: Unable to start activity ComponentInfo{net.majorkernelpanic.spydroid/net.majorkernelpanic.spydroid.ui.SpydroidActivity}: android.view.InflateException: Binary XML file line #52: Binary XML file line #52: Error inflating class com.google.ads.AdView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
     Caused by: android.view.InflateException: Binary XML file line #52: Binary XML file line #52: Error inflating class com.google.ads.AdView
     Caused by: android.view.InflateException: Binary XML file line #52: Error inflating class com.google.ads.AdView
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.ads.AdView" on path: DexPathList[[zip file "/data/app/net.majorkernelpanic.spydroid-JdFKPgwwjViQUFOkk3zFhA==/base.apk"],nativeLibraryDirectories=[/data/app/net.majorkernelpanic.spydroid-JdFKPgwwjViQUFOkk3zFhA==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:610)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:418)
        at android.app.Activity.setContentView(Activity.java:2708)
        at net.majorkernelpanic.spydroid.ui.SpydroidActivity.onCreate(SpydroidActivity.java:86)
        at android.app.Activity.performCreate(Activity.java:7040)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

**Comment by jlivingstonsg** [comment]
Hi.
Love it.
Your link to Google Play is not working.
https://play.google.com/store/apps/details?id=net.majorkernelpanic.spydroid
Your link to Facebook is not working.
https://www.facebook.com/spydroidipcamera

I use also RoboCam.
https://play.google.com/store/apps/details?id=ru.proghouse.robocam&hl=en_US
Is it much work to make your Spydroid to work like RoboCam?

Regards  MagI from Sweden
