### ISSUE TITLE
at net.majorkernelpanic.spydroid.ui.PreviewFragment.onCreateView(PreviewFragment.java:79)

### ISSUE THREAD

**Issue by wujun1206** [fyhertz/spydroid-ipcamera#7]
Caused by: java.lang.ClassCastException: android.view.SurfaceView cannot be cast to net.majorkernelpanic.streaming.gl.SurfaceView
04-30 02:13:59.532: E/AndroidRuntime(28121):    at net.majorkernelpanic.spydroid.ui.PreviewFragment.onCreateView(PreviewFragment.java:79)

**Comment by jamesjara** [comment]
Hi guys, this is not an bug.. it is just a little detail, please check your activity frame, open it in text mode, lookup for the surface element and replace with the majorkernelpanic package namespace, I hope it works, :)

-- <SurfaceView
            android:layout_width="wrap_content"
            android:layout_height="163dp"
            android:id="@+id/surfaceView"
            android:layout_gravity="center_horizontal|top" />

++ <net.majorkernelpanic.streaming.gl.SurfaceView
            android:layout_width="wrap_content"
            android:layout_height="163dp"
            android:id="@+id/surfaceView"
            android:layout_gravity="center_horizontal|top" />

**Comment by jamesjara** [comment]
In some cases, it is just a little detail, please check your activity frame, open it in text mode, lookup for the surface element and replace with the majorkernelpanic package namespace, I hope it works, :)

-- android:layout_width="wrap_content"
android:layout_height="163dp"
android:id="@+id/surfaceView"
android:layout_gravity="center_horizontal|top" />

++ android:layout_width="wrap_content"
android:layout_height="163dp"
android:id="@+id/surfaceView"
android:layout_gravity="center_horizontal|top" />

**Comment by stelad** [comment]
This happens with tablet displays - Simply replace "SurfaceView" with "net.majorkernelpanic.streaming.gl.SurfaceView" in sw600dp/preview.xml
